#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running Gradle on CI:
#   If gradle/wrapper/gradle-wrapper.jar does not exist, run:
#     gradle wrapper --gradle-version=8.5
#
##############################################################################

APP_HOME=$( cd "${0%"${0##*/}"}." > /dev/null && pwd -P ) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: gradle-wrapper.jar not found."
    echo "Run 'gradle wrapper --gradle-version=8.5' to generate it."
    exit 1
fi

# Determine the Java command to use
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

exec "$JAVACMD" \
    -Dorg.gradle.appname="${0##*/}" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
