package com.solo.ledger.data.repository

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.widget.Toast
import androidx.core.content.FileProvider
import com.solo.ledger.data.model.Category
import com.solo.ledger.data.model.Expense
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfExporter {

    fun exportTransactionsAsPdf(
        context: Context,
        expenses: List<Expense>,
        categories: List<Category>,
        currencySymbol: String,
        title: String = "Solo Ledger Statement"
    ) {
        try {
            val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())

            val document = PdfDocument()
            val pageWidth = 595 // A4
            val pageHeight = 842
            var pageNumber = 1
            var yPos = 60f

            val titlePaint = Paint().apply {
                textSize = 18f
                isFakeBoldText = true
                color = android.graphics.Color.BLACK
            }
            val headerPaint = Paint().apply {
                textSize = 11f
                isFakeBoldText = true
                color = android.graphics.Color.DKGRAY
            }
            val bodyPaint = Paint().apply {
                textSize = 10f
                color = android.graphics.Color.BLACK
            }
            val subtlePaint = Paint().apply {
                textSize = 9f
                color = android.graphics.Color.GRAY
            }
            val linePaint = Paint().apply {
                color = android.graphics.Color.LTGRAY
                strokeWidth = 0.5f
            }

            var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            var page = document.startPage(pageInfo)
            var canvas = page.canvas

            // Title
            canvas.drawText(title, 40f, yPos, titlePaint)
            yPos += 24f
            canvas.drawText(
                "Generated: ${dateFormat.format(Date())} | Transactions: ${expenses.size} | Total: $currencySymbol${String.format("%.2f", expenses.sumOf { it.amount })}",
                40f, yPos, subtlePaint
            )
            yPos += 30f

            // Header line
            canvas.drawLine(40f, yPos, pageWidth - 40f, yPos, linePaint)
            yPos += 16f

            // Column headers
            canvas.drawText("Date", 40f, yPos, headerPaint)
            canvas.drawText("Title", 120f, yPos, headerPaint)
            canvas.drawText("Category", 320f, yPos, headerPaint)
            canvas.drawText("Amount", 440f, yPos, headerPaint)
            yPos += 6f
            canvas.drawLine(40f, yPos, pageWidth - 40f, yPos, linePaint)
            yPos += 16f

            // Transactions
            for (expense in expenses) {
                if (yPos > pageHeight - 80) {
                    document.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                    page = document.startPage(pageInfo)
                    canvas = page.canvas
                    yPos = 50f
                }

                val cat = categories.find { it.id == expense.categoryId }
                canvas.drawText(dateFormat.format(Date(expense.date)), 40f, yPos, bodyPaint)
                canvas.drawText(expense.title.take(28), 120f, yPos, bodyPaint)
                canvas.drawText((cat?.name ?: "Other").take(16), 320f, yPos, bodyPaint)
                canvas.drawText("$currencySymbol${String.format("%.2f", expense.amount)}", 440f, yPos, bodyPaint)
                yPos += 18f
            }

            // Footer
            yPos += 20f
            canvas.drawLine(40f, yPos, pageWidth - 40f, yPos, linePaint)
            yPos += 20f
            canvas.drawText("Generated by Solo Ledger", 40f, yPos, subtlePaint)

            document.finishPage(page)

            // Save
            val dir = File(context.getExternalFilesDir(null), "SoloLedger")
            dir.mkdirs()
            val fileDate = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
            val file = File(dir, "statement_$fileDate.pdf")
            FileOutputStream(file).use { document.writeTo(it) }
            document.close()

            // Share
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_SUBJECT, title)
                // For sharing, we use the text fallback since FileProvider needs more setup
                putExtra(Intent.EXTRA_TEXT, "Statement exported to: ${file.absolutePath}")
            }
            context.startActivity(Intent.createChooser(shareIntent, "Export Statement"))

            Toast.makeText(context, "PDF saved: ${file.name}", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Export failed: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }
}
