package com.solo.ledger.ui.theme

import androidx.compose.ui.graphics.Color

// Ledger Dark Theme Colors
object LedgerDarkColors {
    val background = Color(0xFF0F0F0F)
    val surface = Color(0xFF1A1A1A)
    val surfaceVariant = Color(0xFF2A2A2A)
    val surfaceContainer = Color(0xFF1F1F1F)
    val surfaceContainerHigh = Color(0xFF252525)
    val primary = Color(0xFFE8E0D4)
    val primaryContainer = Color(0xFF3D3A36)
    val onPrimary = Color(0xFF1A1A1A)
    val onPrimaryContainer = Color(0xFFE8E0D4)
    val secondary = Color(0xFF8FA68A)
    val secondaryContainer = Color(0xFF2D3B2A)
    val onSecondary = Color(0xFF1A1A1A)
    val onSecondaryContainer = Color(0xFFA8C4A3)
    val tertiary = Color(0xFFD4A090)
    val tertiaryContainer = Color(0xFF3D2E28)
    val onTertiary = Color(0xFF1A1A1A)
    val onTertiaryContainer = Color(0xFFE8B8A8)
    val onBackground = Color(0xFFF0EDE8)
    val onSurface = Color(0xFFE0DCD6)
    val onSurfaceVariant = Color(0xFF9E9A94)
    val outline = Color(0xFF3A3A3A)
    val outlineVariant = Color(0xFF2E2E2E)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF1A1A1A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFF0EDE8)
    val inverseOnSurface = Color(0xFF1A1A1A)
    val scrim = Color(0xFF000000)
}

// Ledger Light Theme Colors
object LedgerLightColors {
    val background = Color(0xFFFAF8F5)
    val surface = Color(0xFFF2EFE9)
    val surfaceVariant = Color(0xFFE8E4DE)
    val surfaceContainer = Color(0xFFF5F2ED)
    val surfaceContainerHigh = Color(0xFFEDEAE4)
    val primary = Color(0xFF1A1A1A)
    val primaryContainer = Color(0xFFE8E0D4)
    val onPrimary = Color(0xFFFAF8F5)
    val onPrimaryContainer = Color(0xFF1A1A1A)
    val secondary = Color(0xFF5E7A58)
    val secondaryContainer = Color(0xFFD4E8D0)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF2D3B2A)
    val tertiary = Color(0xFFB8756A)
    val tertiaryContainer = Color(0xFFF2DDD8)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D2E28)
    val onBackground = Color(0xFF1A1A1A)
    val onSurface = Color(0xFF2A2A2A)
    val onSurfaceVariant = Color(0xFF6B6660)
    val outline = Color(0xFFD0CCC6)
    val outlineVariant = Color(0xFFE0DCD6)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF1A1A1A)
    val inverseOnSurface = Color(0xFFF0EDE8)
    val scrim = Color(0xFF000000)
}

// Emerald Dark Theme Colors
object EmeraldDarkColors {
    val background = Color(0xFF0A0F0A)
    val surface = Color(0xFF141E14)
    val surfaceVariant = Color(0xFF1E2E1E)
    val surfaceContainer = Color(0xFF172217)
    val surfaceContainerHigh = Color(0xFF1C2B1C)
    val primary = Color(0xFF8FD4A0)
    val primaryContainer = Color(0xFF1E3D24)
    val onPrimary = Color(0xFF0A0F0A)
    val onPrimaryContainer = Color(0xFFA8E8B8)
    val secondary = Color(0xFFA0C4B0)
    val secondaryContainer = Color(0xFF1E3028)
    val onSecondary = Color(0xFF0A0F0A)
    val onSecondaryContainer = Color(0xFFB8D8C8)
    val tertiary = Color(0xFFC4D4A0)
    val tertiaryContainer = Color(0xFF2E3D1E)
    val onTertiary = Color(0xFF0A0F0A)
    val onTertiaryContainer = Color(0xFFD8E8B0)
    val onBackground = Color(0xFFE0F0E4)
    val onSurface = Color(0xFFD0E4D4)
    val onSurfaceVariant = Color(0xFF8CA890)
    val outline = Color(0xFF2A3E2A)
    val outlineVariant = Color(0xFF1E2E1E)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0A0F0A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFE0F0E4)
    val inverseOnSurface = Color(0xFF0A0F0A)
    val scrim = Color(0xFF000000)
}

// Emerald Light Theme Colors
object EmeraldLightColors {
    val background = Color(0xFFF5FAF5)
    val surface = Color(0xFFEDF5ED)
    val surfaceVariant = Color(0xFFE0EDE0)
    val surfaceContainer = Color(0xFFF0F7F0)
    val surfaceContainerHigh = Color(0xFFE8F2E8)
    val primary = Color(0xFF2E7D46)
    val primaryContainer = Color(0xFFB8E8C8)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF1E3D24)
    val secondary = Color(0xFF4A7A5E)
    val secondaryContainer = Color(0xFFC8E8D4)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF1E3028)
    val tertiary = Color(0xFF6A8A4A)
    val tertiaryContainer = Color(0xFFD8ECC4)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF2E3D1E)
    val onBackground = Color(0xFF1A2E1A)
    val onSurface = Color(0xFF1E2E1E)
    val onSurfaceVariant = Color(0xFF4A6A4E)
    val outline = Color(0xFFC0D8C4)
    val outlineVariant = Color(0xFFD4E8D8)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF1E2E1E)
    val inverseOnSurface = Color(0xFFE0F0E4)
    val scrim = Color(0xFF000000)
}

// Anime Dark Theme Colors (warm/vibrant dark — inspired by anime aesthetics)
object AnimeDarkColors {
    val background = Color(0xFF0F0D14)
    val surface = Color(0xFF1A1720)
    val surfaceVariant = Color(0xFF2A2530)
    val surfaceContainer = Color(0xFF1E1A24)
    val surfaceContainerHigh = Color(0xFF242028)
    val primary = Color(0xFFE8A0C8)
    val primaryContainer = Color(0xFF3D2434)
    val onPrimary = Color(0xFF0F0D14)
    val onPrimaryContainer = Color(0xFFF0B8D8)
    val secondary = Color(0xFFA8B0E8)
    val secondaryContainer = Color(0xFF24283D)
    val onSecondary = Color(0xFF0F0D14)
    val onSecondaryContainer = Color(0xFFC0C8F0)
    val tertiary = Color(0xFFE8C890)
    val tertiaryContainer = Color(0xFF3D3420)
    val onTertiary = Color(0xFF0F0D14)
    val onTertiaryContainer = Color(0xFFF0D8A8)
    val onBackground = Color(0xFFF0EAF4)
    val onSurface = Color(0xFFE0DAE6)
    val onSurfaceVariant = Color(0xFF9E96A8)
    val outline = Color(0xFF3A3440)
    val outlineVariant = Color(0xFF2E2834)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0F0D14)
    val errorContainer = Color(0xFF3D2024)
    val inverseSurface = Color(0xFFF0EAF4)
    val inverseOnSurface = Color(0xFF0F0D14)
    val scrim = Color(0xFF000000)
}

// Anime Light Theme Colors
object AnimeLightColors {
    val background = Color(0xFFFCF8FE)
    val surface = Color(0xFFF5F0F8)
    val surfaceVariant = Color(0xFFEDE6F2)
    val surfaceContainer = Color(0xFFF8F4FA)
    val surfaceContainerHigh = Color(0xFFF0EAF5)
    val primary = Color(0xFF8A3A6A)
    val primaryContainer = Color(0xFFF0C8E0)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF3D2434)
    val secondary = Color(0xFF4A5090)
    val secondaryContainer = Color(0xFFD4D8F0)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF24283D)
    val tertiary = Color(0xFF8A7040)
    val tertiaryContainer = Color(0xFFF0E0C0)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D3420)
    val onBackground = Color(0xFF1A1420)
    val onSurface = Color(0xFF2A2430)
    val onSurfaceVariant = Color(0xFF6A6070)
    val outline = Color(0xFFD4CCD8)
    val outlineVariant = Color(0xFFE4DCE8)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF2A2430)
    val inverseOnSurface = Color(0xFFF0EAF4)
    val scrim = Color(0xFF000000)
}

// Spider Dark Theme Colors (red/black — inspired by Spider-Man aesthetic)
object SpiderDarkColors {
    val background = Color(0xFF0F0A0A)
    val surface = Color(0xFF1A1414)
    val surfaceVariant = Color(0xFF2A2020)
    val surfaceContainer = Color(0xFF1E1616)
    val surfaceContainerHigh = Color(0xFF241C1C)
    val primary = Color(0xFFE85050)
    val primaryContainer = Color(0xFF3D1818)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFFF08080)
    val secondary = Color(0xFFC0C8D8)
    val secondaryContainer = Color(0xFF282C34)
    val onSecondary = Color(0xFF0F0A0A)
    val onSecondaryContainer = Color(0xFFD4DCE8)
    val tertiary = Color(0xFFE8D060)
    val tertiaryContainer = Color(0xFF3D3418)
    val onTertiary = Color(0xFF0F0A0A)
    val onTertiaryContainer = Color(0xFFF0E080)
    val onBackground = Color(0xFFF0E8E8)
    val onSurface = Color(0xFFE0D8D8)
    val onSurfaceVariant = Color(0xFF9E9494)
    val outline = Color(0xFF3A3030)
    val outlineVariant = Color(0xFF2E2424)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0F0A0A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFF0E8E8)
    val inverseOnSurface = Color(0xFF0F0A0A)
    val scrim = Color(0xFF000000)
}

// Spider Light Theme Colors
object SpiderLightColors {
    val background = Color(0xFFFCF8F8)
    val surface = Color(0xFFF5F0F0)
    val surfaceVariant = Color(0xFFEDE4E4)
    val surfaceContainer = Color(0xFFF8F2F2)
    val surfaceContainerHigh = Color(0xFFF0EAEA)
    val primary = Color(0xFFC62828)
    val primaryContainer = Color(0xFFF0C4C4)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF3D1818)
    val secondary = Color(0xFF404858)
    val secondaryContainer = Color(0xFFD4D8E4)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF282C34)
    val tertiary = Color(0xFF8A7020)
    val tertiaryContainer = Color(0xFFF0E4B0)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D3418)
    val onBackground = Color(0xFF1A1414)
    val onSurface = Color(0xFF2A2020)
    val onSurfaceVariant = Color(0xFF6A6060)
    val outline = Color(0xFFD4CCCC)
    val outlineVariant = Color(0xFFE4DCDC)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF2A2020)
    val inverseOnSurface = Color(0xFFF0E8E8)
    val scrim = Color(0xFF000000)
}

// Square Dark Theme Colors (sharp, brutalist, zero radius)
object SquareDarkColors {
    val background = Color(0xFF0A0A0A)
    val surface = Color(0xFF141414)
    val surfaceVariant = Color(0xFF1E1E1E)
    val surfaceContainer = Color(0xFF181818)
    val surfaceContainerHigh = Color(0xFF222222)
    val primary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFF2C2C2C)
    val onPrimary = Color(0xFF0A0A0A)
    val onPrimaryContainer = Color(0xFFFFFFFF)
    val secondary = Color(0xFFB0B0B0)
    val secondaryContainer = Color(0xFF282828)
    val onSecondary = Color(0xFF0A0A0A)
    val onSecondaryContainer = Color(0xFFD0D0D0)
    val tertiary = Color(0xFF909090)
    val tertiaryContainer = Color(0xFF242424)
    val onTertiary = Color(0xFF0A0A0A)
    val onTertiaryContainer = Color(0xFFB8B8B8)
    val onBackground = Color(0xFFF5F5F5)
    val onSurface = Color(0xFFE8E8E8)
    val onSurfaceVariant = Color(0xFF8A8A8A)
    val outline = Color(0xFF333333)
    val outlineVariant = Color(0xFF282828)
    val error = Color(0xFFFF4444)
    val onError = Color(0xFF0A0A0A)
    val errorContainer = Color(0xFF330000)
    val inverseSurface = Color(0xFFF5F5F5)
    val inverseOnSurface = Color(0xFF0A0A0A)
    val scrim = Color(0xFF000000)
}

// Square Light Theme Colors (sharp, clean, zero radius)
object SquareLightColors {
    val background = Color(0xFFFFFFFF)
    val surface = Color(0xFFF5F5F5)
    val surfaceVariant = Color(0xFFEAEAEA)
    val surfaceContainer = Color(0xFFF8F8F8)
    val surfaceContainerHigh = Color(0xFFF0F0F0)
    val primary = Color(0xFF000000)
    val primaryContainer = Color(0xFFE0E0E0)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF000000)
    val secondary = Color(0xFF505050)
    val secondaryContainer = Color(0xFFD8D8D8)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF2A2A2A)
    val tertiary = Color(0xFF707070)
    val tertiaryContainer = Color(0xFFE4E4E4)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3A3A3A)
    val onBackground = Color(0xFF0A0A0A)
    val onSurface = Color(0xFF1A1A1A)
    val onSurfaceVariant = Color(0xFF5A5A5A)
    val outline = Color(0xFFD0D0D0)
    val outlineVariant = Color(0xFFE0E0E0)
    val error = Color(0xFFCC0000)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFE0E0)
    val inverseSurface = Color(0xFF1A1A1A)
    val inverseOnSurface = Color(0xFFF5F5F5)
    val scrim = Color(0xFF000000)
}
