package com.solo.ledger.ui.theme

import androidx.compose.ui.graphics.Color

// Ledger Dark Theme Colors
object LedgerDarkColors {
    val background = Color(0xFF0F0F0F)
    val surface = Color(0xFF1A1A1A)
    val surfaceVariant = Color(0xFF2A2A2A)
    val surfaceContainer = Color(0xFF1F1F1F)
    val surfaceContainerHigh = Color(0xFF252525)
    val primary = Color(0xFFE8E0D4)
    val primaryContainer = Color(0xFF3D3A36)
    val onPrimary = Color(0xFF1A1A1A)
    val onPrimaryContainer = Color(0xFFE8E0D4)
    val secondary = Color(0xFF8FA68A)
    val secondaryContainer = Color(0xFF2D3B2A)
    val onSecondary = Color(0xFF1A1A1A)
    val onSecondaryContainer = Color(0xFFA8C4A3)
    val tertiary = Color(0xFFD4A090)
    val tertiaryContainer = Color(0xFF3D2E28)
    val onTertiary = Color(0xFF1A1A1A)
    val onTertiaryContainer = Color(0xFFE8B8A8)
    val onBackground = Color(0xFFF0EDE8)
    val onSurface = Color(0xFFE0DCD6)
    val onSurfaceVariant = Color(0xFF9E9A94)
    val outline = Color(0xFF3A3A3A)
    val outlineVariant = Color(0xFF2E2E2E)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF1A1A1A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFF0EDE8)
    val inverseOnSurface = Color(0xFF1A1A1A)
    val scrim = Color(0xFF000000)
}

// Ledger Light Theme Colors
object LedgerLightColors {
    val background = Color(0xFFFAF8F5)
    val surface = Color(0xFFF2EFE9)
    val surfaceVariant = Color(0xFFE8E4DE)
    val surfaceContainer = Color(0xFFF5F2ED)
    val surfaceContainerHigh = Color(0xFFEDEAE4)
    val primary = Color(0xFF1A1A1A)
    val primaryContainer = Color(0xFFE8E0D4)
    val onPrimary = Color(0xFFFAF8F5)
    val onPrimaryContainer = Color(0xFF1A1A1A)
    val secondary = Color(0xFF5E7A58)
    val secondaryContainer = Color(0xFFD4E8D0)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF2D3B2A)
    val tertiary = Color(0xFFB8756A)
    val tertiaryContainer = Color(0xFFF2DDD8)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D2E28)
    val onBackground = Color(0xFF1A1A1A)
    val onSurface = Color(0xFF2A2A2A)
    val onSurfaceVariant = Color(0xFF6B6660)
    val outline = Color(0xFFD0CCC6)
    val outlineVariant = Color(0xFFE0DCD6)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF1A1A1A)
    val inverseOnSurface = Color(0xFFF0EDE8)
    val scrim = Color(0xFF000000)
}

// Emerald Dark Theme Colors
object EmeraldDarkColors {
    val background = Color(0xFF0A0F0A)
    val surface = Color(0xFF141E14)
    val surfaceVariant = Color(0xFF1E2E1E)
    val surfaceContainer = Color(0xFF172217)
    val surfaceContainerHigh = Color(0xFF1C2B1C)
    val primary = Color(0xFF8FD4A0)
    val primaryContainer = Color(0xFF1E3D24)
    val onPrimary = Color(0xFF0A0F0A)
    val onPrimaryContainer = Color(0xFFA8E8B8)
    val secondary = Color(0xFFA0C4B0)
    val secondaryContainer = Color(0xFF1E3028)
    val onSecondary = Color(0xFF0A0F0A)
    val onSecondaryContainer = Color(0xFFB8D8C8)
    val tertiary = Color(0xFFC4D4A0)
    val tertiaryContainer = Color(0xFF2E3D1E)
    val onTertiary = Color(0xFF0A0F0A)
    val onTertiaryContainer = Color(0xFFD8E8B0)
    val onBackground = Color(0xFFE0F0E4)
    val onSurface = Color(0xFFD0E4D4)
    val onSurfaceVariant = Color(0xFF8CA890)
    val outline = Color(0xFF2A3E2A)
    val outlineVariant = Color(0xFF1E2E1E)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0A0F0A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFE0F0E4)
    val inverseOnSurface = Color(0xFF0A0F0A)
    val scrim = Color(0xFF000000)
}

// Emerald Light Theme Colors
object EmeraldLightColors {
    val background = Color(0xFFF5FAF5)
    val surface = Color(0xFFEDF5ED)
    val surfaceVariant = Color(0xFFE0EDE0)
    val surfaceContainer = Color(0xFFF0F7F0)
    val surfaceContainerHigh = Color(0xFFE8F2E8)
    val primary = Color(0xFF2E7D46)
    val primaryContainer = Color(0xFFB8E8C8)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF1E3D24)
    val secondary = Color(0xFF4A7A5E)
    val secondaryContainer = Color(0xFFC8E8D4)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF1E3028)
    val tertiary = Color(0xFF6A8A4A)
    val tertiaryContainer = Color(0xFFD8ECC4)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF2E3D1E)
    val onBackground = Color(0xFF1A2E1A)
    val onSurface = Color(0xFF1E2E1E)
    val onSurfaceVariant = Color(0xFF4A6A4E)
    val outline = Color(0xFFC0D8C4)
    val outlineVariant = Color(0xFFD4E8D8)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF1E2E1E)
    val inverseOnSurface = Color(0xFFE0F0E4)
    val scrim = Color(0xFF000000)
}

// Anime Dark Theme Colors (warm/vibrant dark — inspired by anime aesthetics)
object AnimeDarkColors {
    val background = Color(0xFF0F0D14)
    val surface = Color(0xFF1A1720)
    val surfaceVariant = Color(0xFF2A2530)
    val surfaceContainer = Color(0xFF1E1A24)
    val surfaceContainerHigh = Color(0xFF242028)
    val primary = Color(0xFFE8A0C8)
    val primaryContainer = Color(0xFF3D2434)
    val onPrimary = Color(0xFF0F0D14)
    val onPrimaryContainer = Color(0xFFF0B8D8)
    val secondary = Color(0xFFA8B0E8)
    val secondaryContainer = Color(0xFF24283D)
    val onSecondary = Color(0xFF0F0D14)
    val onSecondaryContainer = Color(0xFFC0C8F0)
    val tertiary = Color(0xFFE8C890)
    val tertiaryContainer = Color(0xFF3D3420)
    val onTertiary = Color(0xFF0F0D14)
    val onTertiaryContainer = Color(0xFFF0D8A8)
    val onBackground = Color(0xFFF0EAF4)
    val onSurface = Color(0xFFE0DAE6)
    val onSurfaceVariant = Color(0xFF9E96A8)
    val outline = Color(0xFF3A3440)
    val outlineVariant = Color(0xFF2E2834)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0F0D14)
    val errorContainer = Color(0xFF3D2024)
    val inverseSurface = Color(0xFFF0EAF4)
    val inverseOnSurface = Color(0xFF0F0D14)
    val scrim = Color(0xFF000000)
}

// Anime Light Theme Colors
object AnimeLightColors {
    val background = Color(0xFFFCF8FE)
    val surface = Color(0xFFF5F0F8)
    val surfaceVariant = Color(0xFFEDE6F2)
    val surfaceContainer = Color(0xFFF8F4FA)
    val surfaceContainerHigh = Color(0xFFF0EAF5)
    val primary = Color(0xFF8A3A6A)
    val primaryContainer = Color(0xFFF0C8E0)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF3D2434)
    val secondary = Color(0xFF4A5090)
    val secondaryContainer = Color(0xFFD4D8F0)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF24283D)
    val tertiary = Color(0xFF8A7040)
    val tertiaryContainer = Color(0xFFF0E0C0)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D3420)
    val onBackground = Color(0xFF1A1420)
    val onSurface = Color(0xFF2A2430)
    val onSurfaceVariant = Color(0xFF6A6070)
    val outline = Color(0xFFD4CCD8)
    val outlineVariant = Color(0xFFE4DCE8)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF2A2430)
    val inverseOnSurface = Color(0xFFF0EAF4)
    val scrim = Color(0xFF000000)
}

// Spider Dark Theme Colors (red/black — inspired by Spider-Man aesthetic)
object SpiderDarkColors {
    val background = Color(0xFF0F0A0A)
    val surface = Color(0xFF1A1414)
    val surfaceVariant = Color(0xFF2A2020)
    val surfaceContainer = Color(0xFF1E1616)
    val surfaceContainerHigh = Color(0xFF241C1C)
    val primary = Color(0xFFE85050)
    val primaryContainer = Color(0xFF3D1818)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFFF08080)
    val secondary = Color(0xFFC0C8D8)
    val secondaryContainer = Color(0xFF282C34)
    val onSecondary = Color(0xFF0F0A0A)
    val onSecondaryContainer = Color(0xFFD4DCE8)
    val tertiary = Color(0xFFE8D060)
    val tertiaryContainer = Color(0xFF3D3418)
    val onTertiary = Color(0xFF0F0A0A)
    val onTertiaryContainer = Color(0xFFF0E080)
    val onBackground = Color(0xFFF0E8E8)
    val onSurface = Color(0xFFE0D8D8)
    val onSurfaceVariant = Color(0xFF9E9494)
    val outline = Color(0xFF3A3030)
    val outlineVariant = Color(0xFF2E2424)
    val error = Color(0xFFCF6679)
    val onError = Color(0xFF0F0A0A)
    val errorContainer = Color(0xFF3D2020)
    val inverseSurface = Color(0xFFF0E8E8)
    val inverseOnSurface = Color(0xFF0F0A0A)
    val scrim = Color(0xFF000000)
}

// Spider Light Theme Colors
object SpiderLightColors {
    val background = Color(0xFFFCF8F8)
    val surface = Color(0xFFF5F0F0)
    val surfaceVariant = Color(0xFFEDE4E4)
    val surfaceContainer = Color(0xFFF8F2F2)
    val surfaceContainerHigh = Color(0xFFF0EAEA)
    val primary = Color(0xFFC62828)
    val primaryContainer = Color(0xFFF0C4C4)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF3D1818)
    val secondary = Color(0xFF404858)
    val secondaryContainer = Color(0xFFD4D8E4)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF282C34)
    val tertiary = Color(0xFF8A7020)
    val tertiaryContainer = Color(0xFFF0E4B0)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3D3418)
    val onBackground = Color(0xFF1A1414)
    val onSurface = Color(0xFF2A2020)
    val onSurfaceVariant = Color(0xFF6A6060)
    val outline = Color(0xFFD4CCCC)
    val outlineVariant = Color(0xFFE4DCDC)
    val error = Color(0xFFB3261E)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFF9DEDC)
    val inverseSurface = Color(0xFF2A2020)
    val inverseOnSurface = Color(0xFFF0E8E8)
    val scrim = Color(0xFF000000)
}

// Square Dark Theme Colors (sharp, brutalist, zero radius)
object SquareDarkColors {
    val background = Color(0xFF0A0A0A)
    val surface = Color(0xFF141414)
    val surfaceVariant = Color(0xFF1E1E1E)
    val surfaceContainer = Color(0xFF181818)
    val surfaceContainerHigh = Color(0xFF222222)
    val primary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFF2C2C2C)
    val onPrimary = Color(0xFF0A0A0A)
    val onPrimaryContainer = Color(0xFFFFFFFF)
    val secondary = Color(0xFFB0B0B0)
    val secondaryContainer = Color(0xFF282828)
    val onSecondary = Color(0xFF0A0A0A)
    val onSecondaryContainer = Color(0xFFD0D0D0)
    val tertiary = Color(0xFF909090)
    val tertiaryContainer = Color(0xFF242424)
    val onTertiary = Color(0xFF0A0A0A)
    val onTertiaryContainer = Color(0xFFB8B8B8)
    val onBackground = Color(0xFFF5F5F5)
    val onSurface = Color(0xFFE8E8E8)
    val onSurfaceVariant = Color(0xFF8A8A8A)
    val outline = Color(0xFF333333)
    val outlineVariant = Color(0xFF282828)
    val error = Color(0xFFFF4444)
    val onError = Color(0xFF0A0A0A)
    val errorContainer = Color(0xFF330000)
    val inverseSurface = Color(0xFFF5F5F5)
    val inverseOnSurface = Color(0xFF0A0A0A)
    val scrim = Color(0xFF000000)
}

// Square Light Theme Colors (sharp, clean, zero radius)
object SquareLightColors {
    val background = Color(0xFFFFFFFF)
    val surface = Color(0xFFF5F5F5)
    val surfaceVariant = Color(0xFFEAEAEA)
    val surfaceContainer = Color(0xFFF8F8F8)
    val surfaceContainerHigh = Color(0xFFF0F0F0)
    val primary = Color(0xFF000000)
    val primaryContainer = Color(0xFFE0E0E0)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF000000)
    val secondary = Color(0xFF505050)
    val secondaryContainer = Color(0xFFD8D8D8)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF2A2A2A)
    val tertiary = Color(0xFF707070)
    val tertiaryContainer = Color(0xFFE4E4E4)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF3A3A3A)
    val onBackground = Color(0xFF0A0A0A)
    val onSurface = Color(0xFF1A1A1A)
    val onSurfaceVariant = Color(0xFF5A5A5A)
    val outline = Color(0xFFD0D0D0)
    val outlineVariant = Color(0xFFE0E0E0)
    val error = Color(0xFFCC0000)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFE0E0)
    val inverseSurface = Color(0xFF1A1A1A)
    val inverseOnSurface = Color(0xFFF5F5F5)
    val scrim = Color(0xFF000000)
}

// Ocean Dark Theme
object OceanDarkColors {
    val background = Color(0xFF0A1628)
    val surface = Color(0xFF122240)
    val surfaceVariant = Color(0xFF1A3058)
    val primary = Color(0xFF64B5F6)
    val primaryContainer = Color(0xFF1A3A6B)
    val onPrimary = Color(0xFF0A1628)
    val onPrimaryContainer = Color(0xFF90CAF9)
    val secondary = Color(0xFF80CBC4)
    val secondaryContainer = Color(0xFF1A3D3A)
    val onSecondary = Color(0xFF0A1628)
    val onSecondaryContainer = Color(0xFFA0DCD6)
    val tertiary = Color(0xFFCE93D8)
    val tertiaryContainer = Color(0xFF2E1A3D)
    val onTertiary = Color(0xFF0A1628)
    val onTertiaryContainer = Color(0xFFE1BEE7)
    val onBackground = Color(0xFFE3F2FD)
    val onSurface = Color(0xFFBBDEFB)
    val onSurfaceVariant = Color(0xFF7BAED4)
    val outline = Color(0xFF2A4570)
    val outlineVariant = Color(0xFF1E3558)
    val error = Color(0xFFEF5350)
    val onError = Color(0xFF0A1628)
    val errorContainer = Color(0xFF3D1A1A)
    val inverseSurface = Color(0xFFE3F2FD)
    val inverseOnSurface = Color(0xFF0A1628)
    val scrim = Color(0xFF000000)
}

// Ocean Light Theme
object OceanLightColors {
    val background = Color(0xFFF5FAFF)
    val surface = Color(0xFFEDF5FF)
    val surfaceVariant = Color(0xFFE0EEFF)
    val primary = Color(0xFF1565C0)
    val primaryContainer = Color(0xFFBBDEFB)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF0D47A1)
    val secondary = Color(0xFF00897B)
    val secondaryContainer = Color(0xFFB2DFDB)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF004D40)
    val tertiary = Color(0xFF7B1FA2)
    val tertiaryContainer = Color(0xFFE1BEE7)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF4A148C)
    val onBackground = Color(0xFF0D1B2A)
    val onSurface = Color(0xFF1A2E4A)
    val onSurfaceVariant = Color(0xFF4A6A8A)
    val outline = Color(0xFFB0C8E8)
    val outlineVariant = Color(0xFFD0E4F8)
    val error = Color(0xFFD32F2F)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFCDD2)
    val inverseSurface = Color(0xFF1A2E4A)
    val inverseOnSurface = Color(0xFFE3F2FD)
    val scrim = Color(0xFF000000)
}

// Sunset Dark Theme
object SunsetDarkColors {
    val background = Color(0xFF1A0E0A)
    val surface = Color(0xFF2A1810)
    val surfaceVariant = Color(0xFF3A2218)
    val primary = Color(0xFFFFAB40)
    val primaryContainer = Color(0xFF4A2800)
    val onPrimary = Color(0xFF1A0E0A)
    val onPrimaryContainer = Color(0xFFFFCC80)
    val secondary = Color(0xFFFF7043)
    val secondaryContainer = Color(0xFF4A1A0A)
    val onSecondary = Color(0xFF1A0E0A)
    val onSecondaryContainer = Color(0xFFFFAB91)
    val tertiary = Color(0xFFFFD54F)
    val tertiaryContainer = Color(0xFF4A3800)
    val onTertiary = Color(0xFF1A0E0A)
    val onTertiaryContainer = Color(0xFFFFE082)
    val onBackground = Color(0xFFFFF3E0)
    val onSurface = Color(0xFFFFE0B2)
    val onSurfaceVariant = Color(0xFFCC9060)
    val outline = Color(0xFF4A3020)
    val outlineVariant = Color(0xFF3A2418)
    val error = Color(0xFFFF5252)
    val onError = Color(0xFF1A0E0A)
    val errorContainer = Color(0xFF4A1A1A)
    val inverseSurface = Color(0xFFFFF3E0)
    val inverseOnSurface = Color(0xFF1A0E0A)
    val scrim = Color(0xFF000000)
}

// Sunset Light Theme
object SunsetLightColors {
    val background = Color(0xFFFFFBF5)
    val surface = Color(0xFFFFF5E8)
    val surfaceVariant = Color(0xFFFFEDD8)
    val primary = Color(0xFFE65100)
    val primaryContainer = Color(0xFFFFCC80)
    val onPrimary = Color(0xFFFFFFFF)
    val onPrimaryContainer = Color(0xFF4A2800)
    val secondary = Color(0xFFBF360C)
    val secondaryContainer = Color(0xFFFFAB91)
    val onSecondary = Color(0xFFFFFFFF)
    val onSecondaryContainer = Color(0xFF4A1A0A)
    val tertiary = Color(0xFFF57F17)
    val tertiaryContainer = Color(0xFFFFE082)
    val onTertiary = Color(0xFFFFFFFF)
    val onTertiaryContainer = Color(0xFF4A3800)
    val onBackground = Color(0xFF2A1810)
    val onSurface = Color(0xFF3A2218)
    val onSurfaceVariant = Color(0xFF7A5040)
    val outline = Color(0xFFE0C8B8)
    val outlineVariant = Color(0xFFF0DED0)
    val error = Color(0xFFD32F2F)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFCDD2)
    val inverseSurface = Color(0xFF3A2218)
    val inverseOnSurface = Color(0xFFFFF3E0)
    val scrim = Color(0xFF000000)
}

// Midnight Dark Theme (deep purple/indigo)
object MidnightDarkColors {
    val background = Color(0xFF0D0D1A)
    val surface = Color(0xFF141428)
    val surfaceVariant = Color(0xFF1E1E38)
    val primary = Color(0xFFB388FF)
    val primaryContainer = Color(0xFF2A1A50)
    val onPrimary = Color(0xFF0D0D1A)
    val onPrimaryContainer = Color(0xFFD1B3FF)
    val secondary = Color(0xFF82B1FF)
    val secondaryContainer = Color(0xFF1A2A50)
    val onSecondary = Color(0xFF0D0D1A)
    val onSecondaryContainer = Color(0xFFAAC8FF)
    val tertiary = Color(0xFFF48FB1)
    val tertiaryContainer = Color(0xFF3D1A28)
    val onTertiary = Color(0xFF0D0D1A)
    val onTertiaryContainer = Color(0xFFF8BBD0)
    val onBackground = Color(0xFFEDE7F6)
    val onSurface = Color(0xFFD1C4E9)
    val onSurfaceVariant = Color(0xFF9080B0)
    val outline = Color(0xFF2E2850)
    val outlineVariant = Color(0xFF221E40)
    val error = Color(0xFFFF5252)
    val onError = Color(0xFF0D0D1A)
    val errorContainer = Color(0xFF3D1A1A)
    val inverseSurface = Color(0xFFEDE7F6)
    val inverseOnSurface = Color(0xFF0D0D1A)
    val scrim = Color(0xFF000000)
}

// Rose Dark Theme
object RoseDarkColors {
    val background = Color(0xFF140A10)
    val surface = Color(0xFF1E1218)
    val surfaceVariant = Color(0xFF2E1A24)
    val primary = Color(0xFFF48FB1)
    val primaryContainer = Color(0xFF3D1A28)
    val onPrimary = Color(0xFF140A10)
    val onPrimaryContainer = Color(0xFFF8BBD0)
    val secondary = Color(0xFFCE93D8)
    val secondaryContainer = Color(0xFF2E1A3D)
    val onSecondary = Color(0xFF140A10)
    val onSecondaryContainer = Color(0xFFE1BEE7)
    val tertiary = Color(0xFFFFAB91)
    val tertiaryContainer = Color(0xFF3D1A0A)
    val onTertiary = Color(0xFF140A10)
    val onTertiaryContainer = Color(0xFFFFCCBC)
    val onBackground = Color(0xFFFCE4EC)
    val onSurface = Color(0xFFF8BBD0)
    val onSurfaceVariant = Color(0xFFB06080)
    val outline = Color(0xFF3D2030)
    val outlineVariant = Color(0xFF2E1824)
    val error = Color(0xFFFF5252)
    val onError = Color(0xFF140A10)
    val errorContainer = Color(0xFF3D1A1A)
    val inverseSurface = Color(0xFFFCE4EC)
    val inverseOnSurface = Color(0xFF140A10)
    val scrim = Color(0xFF000000)
}

// Mint Dark Theme
object MintDarkColors {
    val background = Color(0xFF0A1410)
    val surface = Color(0xFF101E18)
    val surfaceVariant = Color(0xFF182E24)
    val primary = Color(0xFF80CBC4)
    val primaryContainer = Color(0xFF1A3D38)
    val onPrimary = Color(0xFF0A1410)
    val onPrimaryContainer = Color(0xFFA0DCD6)
    val secondary = Color(0xFFA5D6A7)
    val secondaryContainer = Color(0xFF1A3D1E)
    val onSecondary = Color(0xFF0A1410)
    val onSecondaryContainer = Color(0xFFC8E6C9)
    val tertiary = Color(0xFF80DEEA)
    val tertiaryContainer = Color(0xFF1A3D40)
    val onTertiary = Color(0xFF0A1410)
    val onTertiaryContainer = Color(0xFFB2EBF2)
    val onBackground = Color(0xFFE0F2F1)
    val onSurface = Color(0xFFB2DFDB)
    val onSurfaceVariant = Color(0xFF70A8A0)
    val outline = Color(0xFF204038)
    val outlineVariant = Color(0xFF18302A)
    val error = Color(0xFFEF5350)
    val onError = Color(0xFF0A1410)
    val errorContainer = Color(0xFF3D1A1A)
    val inverseSurface = Color(0xFFE0F2F1)
    val inverseOnSurface = Color(0xFF0A1410)
    val scrim = Color(0xFF000000)
}
