package com.solo.ledger.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class LedgerExtendedColors(
    val primary: Color,
    val secondary: Color,
    val background: Color,
    val surface: Color,
    val card: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val muted: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val outline: Color,
    val navSelected: Color,
    val chartOne: Color,
    val chartTwo: Color,
    val chartThree: Color,
)

enum class LedgerTheme {
    LedgerLight,
    LedgerDark,
    EmeraldLight,
    EmeraldDark,
    AnimeLight,
    AnimeDark,
    SpiderLight,
    SpiderDark,
}

internal fun LedgerTheme.colors(): LedgerExtendedColors = when (this) {
    LedgerTheme.LedgerLight -> LedgerExtendedColors(
        primary = Color(0xFF16A34A),
        secondary = Color(0xFF4ADE80),
        background = Color(0xFFFFFFFF),
        surface = Color(0xFFF8FAFC),
        card = Color(0xFFFFFFFF),
        textPrimary = Color(0xFF0F172A),
        textSecondary = Color(0xFF475569),
        muted = Color(0xFF64748B),
        success = Color(0xFF16A34A),
        warning = Color(0xFFD97706),
        error = Color(0xFFDC2626),
        outline = Color(0xFFE2E8F0),
        navSelected = Color(0xFFE7F8EE),
        chartOne = Color(0xFF16A34A),
        chartTwo = Color(0xFF15803D),
        chartThree = Color(0xFF86EFAC),
    )
    LedgerTheme.LedgerDark -> LedgerExtendedColors(
        primary = Color(0xFF22C55E),
        secondary = Color(0xFF4ADE80),
        background = Color(0xFF0B0F0C),
        surface = Color(0xFF121815),
        card = Color(0xFF1A211D),
        textPrimary = Color(0xFFF8FAFC),
        textSecondary = Color(0xFFCBD5E1),
        muted = Color(0xFF94A3B8),
        success = Color(0xFF22C55E),
        warning = Color(0xFFF59E0B),
        error = Color(0xFFEF4444),
        outline = Color(0xFF26352D),
        navSelected = Color(0xFF173B25),
        chartOne = Color(0xFF22C55E),
        chartTwo = Color(0xFF86EFAC),
        chartThree = Color(0xFF15803D),
    )
    LedgerTheme.EmeraldLight -> LedgerExtendedColors(
        primary = Color(0xFF047857),
        secondary = Color(0xFF10B981),
        background = Color(0xFFFAFFFC),
        surface = Color(0xFFF0FDF4),
        card = Color(0xFFFFFFFF),
        textPrimary = Color(0xFF062C20),
        textSecondary = Color(0xFF315D4D),
        muted = Color(0xFF5F8174),
        success = Color(0xFF047857),
        warning = Color(0xFFB45309),
        error = Color(0xFFB91C1C),
        outline = Color(0xFFD7F3E2),
        navSelected = Color(0xFFE2F8EC),
        chartOne = Color(0xFF047857),
        chartTwo = Color(0xFF10B981),
        chartThree = Color(0xFF6EE7B7),
    )
    LedgerTheme.EmeraldDark -> LedgerExtendedColors(
        primary = Color(0xFF34D399),
        secondary = Color(0xFF6EE7B7),
        background = Color(0xFF07130D),
        surface = Color(0xFF0B1A12),
        card = Color(0xFF102018),
        textPrimary = Color(0xFFF1FFF8),
        textSecondary = Color(0xFFC5EADC),
        muted = Color(0xFF8DB8A6),
        success = Color(0xFF34D399),
        warning = Color(0xFFF59E0B),
        error = Color(0xFFF87171),
        outline = Color(0xFF1F3B2E),
        navSelected = Color(0xFF143625),
        chartOne = Color(0xFF34D399),
        chartTwo = Color(0xFF6EE7B7),
        chartThree = Color(0xFF059669),
    )
    LedgerTheme.AnimeLight -> LedgerExtendedColors(
        primary = Color(0xFF7C3AED),
        secondary = Color(0xFFF97316),
        background = Color(0xFFFFFBF7),
        surface = Color(0xFFFFF7ED),
        card = Color(0xFFFFFFFF),
        textPrimary = Color(0xFF21122E),
        textSecondary = Color(0xFF5B456B),
        muted = Color(0xFF7C688A),
        success = Color(0xFF16A34A),
        warning = Color(0xFFF97316),
        error = Color(0xFFDC2626),
        outline = Color(0xFFF1D9C5),
        navSelected = Color(0xFFF3E8FF),
        chartOne = Color(0xFF7C3AED),
        chartTwo = Color(0xFFF97316),
        chartThree = Color(0xFFA78BFA),
    )
    LedgerTheme.AnimeDark -> LedgerExtendedColors(
        primary = Color(0xFFA78BFA),
        secondary = Color(0xFFFB923C),
        background = Color(0xFF141018),
        surface = Color(0xFF1A1321),
        card = Color(0xFF211827),
        textPrimary = Color(0xFFFFF7ED),
        textSecondary = Color(0xFFE9D5FF),
        muted = Color(0xFFC4B5FD),
        success = Color(0xFF4ADE80),
        warning = Color(0xFFFB923C),
        error = Color(0xFFF87171),
        outline = Color(0xFF3A2844),
        navSelected = Color(0xFF332045),
        chartOne = Color(0xFFA78BFA),
        chartTwo = Color(0xFFFB923C),
        chartThree = Color(0xFF7C3AED),
    )
    LedgerTheme.SpiderLight -> LedgerExtendedColors(
        primary = Color(0xFFB91C1C),
        secondary = Color(0xFF0F172A),
        background = Color(0xFFFFFFFF),
        surface = Color(0xFFF8FAFC),
        card = Color(0xFFFFFFFF),
        textPrimary = Color(0xFF0F172A),
        textSecondary = Color(0xFF475569),
        muted = Color(0xFF64748B),
        success = Color(0xFF16A34A),
        warning = Color(0xFFD97706),
        error = Color(0xFFB91C1C),
        outline = Color(0xFFE2E8F0),
        navSelected = Color(0xFFFEE2E2),
        chartOne = Color(0xFFB91C1C),
        chartTwo = Color(0xFF0F172A),
        chartThree = Color(0xFFEF4444),
    )
    LedgerTheme.SpiderDark -> LedgerExtendedColors(
        primary = Color(0xFFF87171),
        secondary = Color(0xFFCBD5E1),
        background = Color(0xFF090B10),
        surface = Color(0xFF0F131B),
        card = Color(0xFF151923),
        textPrimary = Color(0xFFF8FAFC),
        textSecondary = Color(0xFFCBD5E1),
        muted = Color(0xFF94A3B8),
        success = Color(0xFF22C55E),
        warning = Color(0xFFF59E0B),
        error = Color(0xFFF87171),
        outline = Color(0xFF262D3B),
        navSelected = Color(0xFF3B1518),
        chartOne = Color(0xFFF87171),
        chartTwo = Color(0xFFCBD5E1),
        chartThree = Color(0xFFB91C1C),
    )
}
